theme: jekyll-theme-slate
title: This is anuj pachauri homepage
description: Feel free to bookmarks my page get update of my repos

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Anuj Pachauri'
tagline:          '#include<code>'
description:      'Blogger | Nadal-ion'
url:              https://anujaryan.github.io
baseurl:          ""

author:
  name:           'Anuj Pachauri'
  url:            https://twitter.com/edorado93
  gravatar_md5:   e51882718aefa4b1acf0f59ab2edc916
  github:         anujaryan
  linkedin:       anujpachauri
  medium:         anujpachauri
 
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook: anujpachauri
  flickr:
  github: anujpachauri
  instagram:
  linkedin: anujpachauri
  pinterest:
  rss: feed
  twitter: anujpachauri
  stackoverflow: users/6826197/apachauri
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +anujpachauri 

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-gist
  - jekyll-paginate
